### ISSUE TITLE
Dear Jeff, I am making a compiler now and it is the last phase. Close this issue and remake the docs. I am gonna make a test script under compiler you can see how ubiquit is programmed. After you got the idea then remake the docs. The docs are wrong.

### ISSUE THREAD

**Issue by AristodamusAdairs** [JeffTheK/ubiquit#32]

**Comment by AristodamusAdairs** [comment]
https://github.com/JeffTheK/ubiquit/blob/main/src/Compiler/source/test.ubi

**Comment by AristodamusAdairs** [comment]
This is a example script of Math library. We have a inbuilt math library. Dont think we can make it a language to build everything bcz we need to do very extensive programming plus libraries in ubiquit

**Comment by JeffTheK** [comment]
You mean to make the docs match the code in `test.ubi`? Also we have different keywords in [tokencs.cpp](https://github.com/JeffTheK/ubiquit/blob/main/src/Parser/source/tokens.cpp), we should fix it.

**Comment by JeffTheK** [comment]
Also we have different base types in docs. Can you please list what basic types we should have. And I also want to know what type `number` is. Is it just a float? Also should these types be their own classes with functions?

**Comment by AristodamusAdairs** [comment]
Yes dude change your docs

**Comment by AristodamusAdairs** [comment]
According to test.ub

**Comment by JeffTheK** [comment]
Can you also please provide an example of class

**Comment by AristodamusAdairs** [comment]
You mean foot prints?

**Comment by JeffTheK** [comment]
I mean the syntax for how to declare a class

**Comment by AristodamusAdairs** [comment]
Sure but you said fiction but it is fun, fun is a token for function,

**Comment by AristodamusAdairs** [comment]
Sorry fiction is function

**Comment by JeffTheK** [comment]
Oh I found the problem. We have different tokens in parser and in compiler.

**Comment by AristodamusAdairs** [comment]
Oh I see!

**Comment by AristodamusAdairs** [comment]
A parser just reads a text into an internal, more abstract representation, often a tree or graph of some sort. A compiler translates such an internal representation into another format. Most often this means converting source code into executable programs.

**Comment by AristodamusAdairs** [comment]
They are reserved tokens! Parser and Compiler is nevertheless same

**Comment by JeffTheK** [comment]
Ah ok.

**Comment by AristodamusAdairs** [comment]
https://github.com/JeffTheK/ubiquit/blob/main/src/Tokenizer/source/tokens.cpp Only trust this!

**Comment by AristodamusAdairs** [comment]
Also we get xcode so everything can run on Mac!

**Comment by JeffTheK** [comment]
I am still a little bit confused about tokens. The tokens lookup is used to find if parsed word is a keyword. In the file string `fun` defines the `reserved_token::kw_fun`. So if I pass this text `fun void foo() {}` It's OK. But if I use `function` instead it won't recognize the keyword, right?

**Comment by JeffTheK** [comment]
the https://github.com/JeffTheK/ubiquit/blob/main/src/Tokenizer/source/tokens.cpp defines `reserved_token::kw_fun` as `"fun"`, isn't it supposed to be the same as in the compiler tokens.cpp? (it's `"function"` there)

**Comment by AristodamusAdairs** [comment]
you hae a correct point sir! We use fun and change functiom. fun is fine

**Comment by AristodamusAdairs** [comment]
ahh my typo

**Comment by JeffTheK** [comment]
So we use `fun` to define functions?

**Comment by AristodamusAdairs** [comment]
ya, Thats correct. Test.ubi is wrong file now

**Comment by JeffTheK** [comment]
Ah ok.

**Comment by AristodamusAdairs** [comment]
thats because a token has a same symbol like for add I use + but for function the symbol is fun like in lisp it is defun

**Comment by AristodamusAdairs** [comment]
I am mad about our programming language!

**Comment by JeffTheK** [comment]
I get it. I will now update my docs according to Parser tokens.cpp

**Comment by JeffTheK** [comment]
So a function is declared like this
````
fun add_nums(number a, number b) {
    return a + b
}
````

**Comment by AristodamusAdairs** [comment]
correct! You got it!

**Comment by AristodamusAdairs** [comment]
Our language is nearly like C++

**Comment by JeffTheK** [comment]
Also one last question, is type `number` a floating point?

**Comment by JeffTheK** [comment]
One important thing I want to say, is that this language was originally supposed to be a quick scripting one, easy to use like python, but looks like C#.  If you want to create a serious compiled language I think we should rather create a different repository. I also have a good book to read if you want to learn more about making programming languages [link](http://index-of.es/OS/Create%20Your%20Own%20Programming%20Language.pdf).

**Comment by AristodamusAdairs** [comment]
Dude just do not say I wasted our time! Cries************

**Comment by JeffTheK** [comment]
Nah, we can still work on it. I just want to know what ideas specifically we should focus on this language. I am also not very good at writing compilers that's why I've only written a documentation. It's a good idea to design the language before writing a compiler.

**Comment by AristodamusAdairs** [comment]
We have to change the docs and say that this language is complicated.  The language is designed. Takes a tissue**********Sobs slowly********

**Comment by JeffTheK** [comment]
Don't cry bro, I will be with you and help with anything I can.

**Comment by AristodamusAdairs** [comment]
Hey!!!Takes a tissue**********Getting ready on docs!Lets change the docs
