### ISSUE TITLE
Lack of Correct Documentation

### ISSUE THREAD

**Issue by AitzazImtiaz** [JeffTheK/ubiquit#35]
No prob. ;)

**Comment by AitzazImtiaz** [comment]
I am done

**Comment by AitzazImtiaz** [comment]
*sighs* do laundry of your readme and diy and edit that.
;)

**Comment by JeffTheK** [comment]
Thank you ;)

**Comment by AitzazImtiaz** [comment]
Documentation is up to date. You can check that but consider the readme job bro ;)
No thanks between friends. Rule 1 in my friendship.

**Comment by JeffTheK** [comment]
Ok, I will clean up the readme later

**Comment by AitzazImtiaz** [comment]
I am doing it now 😡

**Comment by AitzazImtiaz** [comment]
I am going to launder it

**Comment by AitzazImtiaz** [comment]
**gets active**

**Comment by AitzazImtiaz** [comment]
I have free time all day
